### ISSUE TITLE
Dropdown does not work

### ISSUE THREAD

**Issue by PortNumber53** [calidion/Vite-React-Typescript-Sass-Bootstrap-Starter#1]
I've cloned your repo, and copied and pasted the sample Nav bar with Dropdown from the official react-bootstrap documentation, and the dropdown does not work.;

I also tried adding `import * as bootstrap from "bootstrap";` to `App.tsx`, but still couldn't get it to work.

**Comment by calidion** [comment]
React bootstrap is another project. This project is a starter for bootstrap using react.
